### ISSUE TITLE
formatting fails for size > 1mb

### ISSUE THREAD

**Issue by chris-schra** [rickkas7/SpiffsParticleRK#2]
First of all: thanks for all your libs! great work!

I have a W25Q128 and if I try to run the sample, it will only work with
fs.withPhysicalSize(1024 * 1024);

I tried fs.withPhysicalSize(16*1024 * 1024);
(and 2, 4 and 8) but this yields "NO_FS" error (-1025)

**Comment by rickkas7** [comment]
I have a W25Q128 and it does work. However, once you've formatted it as 1 MB you may find it difficult to reformat it, because format won't overwrite a seemingly valid file system. Just call the chipErase() method on the spiFlash object and you should be able to use all of the flash again.

**Comment by chris-schra** [comment]
thanks for the quick reply!

I tried like this

`

    iFlash.begin();
    spiFlash.chipErase();
    fs.withPhysicalSize(4*1024 * 1024);


    s32_t res = fs.mountAndFormatIfNecessary();
    Log.info("mount res=%d", res);`

but still:

> 0000020363 [app.spiffs] INFO: format res=0
> 0000020363 [app.spiffs] INFO: mount after format res=-10025
> 0000020363 [app] INFO: mount res=-10025

**Comment by rickkas7** [comment]
Make sure you have the Winbond SpiFlash object, as the timeout will be too short if you have one of the other ones selected.

```
SpiFlashWinbond spiFlash(SPI1, D5)
```

You could also try using:

```
fs.erase();
```

before trying to mount. 

I just tested it using a W25Q128 and it was able to make a 16 MB file system overwriting a 128K file system using fs.erase.

**Comment by chris-schra** [comment]
Hi and thanks again,

I think it turned out that it was a threading problem or maybe flashing the chip with a different lib previously just for testing. I just took another chip and everything works great, thanks!
