### ISSUE TITLE
flash is not mounting

### ISSUE THREAD

**Issue by medida** [rickkas7/SpiffsParticleRK#4]
Hi

I'm now using the chips which you specified (IS25LQ020B-JNLE)

but upon running the code its not proceeding into the writing the file / returning the file

`0000004319 [comm.protocol] INFO: rcv'd message type=13
Setup --------------------
SPIFFS_mount  sz:0 logpgsz:0 logblksz:0 perasz:0 addr:00000000 fdsz:128 cachesz:1192
0000008278 [app.spiffs] INFO: mount res=-10025
erase 00000000:4096
erase 00001000:4096
erase 00002000:4096
erase 00003000:4096
erase 00004000:4096
erase 00005000:4096
erase 00006000:4096
erase 00007000:4096
erase 00008000:4096
erase 00009000:4096
erase 0000a000:4096
erase 0000b000:4096
erase 0000c000:4096
erase 0000d000:4096
erase 0000e000:4096
erase 0000f000:4096
erase 00010000:4096
erase 00011000:4096
erase 00012000:4096
erase 00013000:4096
erase 00014000:4096
erase 00015000:4096
erase 00016000:4096
erase 00017000:4096
erase 00018000:4096
erase 00019000:4096
erase 0001a000:4096
erase 0001b000:4096
erase 0001c000:4096
erase 0001d000:4096
erase 0001e000:4096
erase 0001f000:4096
erase 00020000:4096
erase 00021000:4096
erase 00022000:4096
erase 00023000:4096
erase 00024000:4096
erase 00025000:4096
erase 00026000:4096
erase 00027000:4096
erase 00028000:4096
erase 00029000:4096
erase 0002a000:4096
erase 0002b000:4096
erase 0002c000:4096
erase 0002d000:4096
erase 0002e000:4096
erase 0002f000:4096
erase 00030000:4096
erase 00031000:4096
erase 00032000:4096
erase 00033000:4096
erase 00034000:4096
erase 00035000:4096
erase 00036000:4096
erase 00037000:4096
erase 00038000:4096
erase 00039000:4096
erase 0003a000:4096
erase 0003b000:4096
erase 0003c000:4096
erase 0003d000:4096
erase 0003e000:4096
erase 0003f000:4096
erase 00040000:4096
erase 00041000:4096
erase 00042000:4096
erase 00043000:4096
erase 00044000:4096
erase 00045000:4096
erase 00046000:4096
erase 00047000:4096
erase 00048000:4096
erase 00049000:4096
erase 0004a000:4096
erase 0004b000:4096
erase 0004c000:4096
erase 0004d000:4096
erase 0004e000:4096
erase 0004f000:4096
erase 00050000:4096
erase 00051000:4096
erase 00052000:4096
erase 00053000:4096
erase 00054000:4096
erase 00055000:4096
erase 00056000:4096
erase 00057000:4096
erase 00058000:4096
erase 00059000:4096
erase 0005a000:4096
erase 0005b000:4096
erase 0005c000:4096
erase 0005d000:4096
erase 0005e000:4096
erase 0005f000:4096
erase 00060000:4096
erase 00061000:4096
erase 00062000:4096
erase 00063000:4096
erase 00064000:4096
erase 00065000:4096
erase 00066000:4096
erase 00067000:4096
erase 00068000:4096
erase 00069000:4096
erase 0006a000:4096
erase 0006b000:4096
erase 0006c000:4096
erase 0006d000:4096
erase 0006e000:4096
erase 0006f000:4096
erase 00070000:4096
erase 00071000:4096
erase 00072000:4096
erase 00073000:4096
erase 00074000:4096
erase 00075000:4096
erase 00076000:4096
erase 00077000:4096
erase 00078000:4096
erase 00079000:4096
erase 0007a000:4096
erase 0007b000:4096
erase 0007c000:4096
erase 0007d000:4096
erase 0007e000:4096
erase 0007f000:4096
erase 00080000:4096
erase 00081000:4096
erase 00082000:4096
erase 00083000:4096
erase 00084000:4096
erase 00085000:4096
erase 00086000:4096
erase 00087000:4096
erase 00088000:4096
erase 00089000:4096
erase 0008a000:4096
erase 0008b000:4096
erase 0008c000:4096
erase 0008d000:4096
erase 0008e000:4096
erase 0008f000:4096
erase 00090000:4096
erase 00091000:4096
erase 00092000:4096
erase 00093000:4096
erase 00094000:4096
erase 00095000:4096
erase 00096000:4096
erase 00097000:4096
erase 00098000:4096
erase 00099000:4096
erase 0009a000:4096
erase 0009b000:4096
erase 0009c000:4096
erase 0009d000:4096
erase 0009e000:4096
erase 0009f000:4096
erase 000a0000:4096
erase 000a1000:4096
erase 000a2000:4096
erase 000a3000:4096
erase 000a4000:4096
erase 000a5000:4096
erase 000a6000:4096
erase 000a7000:4096
erase 000a8000:4096
erase 000a9000:4096
erase 000aa000:4096
erase 000ab000:4096
erase 000ac000:4096
erase 000ad000:4096
erase 000ae000:4096
erase 000af000:4096
erase 000b0000:4096
erase 000b1000:4096
erase 000b2000:4096
erase 000b3000:4096
erase 000b4000:4096
erase 000b5000:4096
erase 000b6000:4096
erase 000b7000:4096
erase 000b8000:4096
erase 000b9000:4096
erase 000ba000:4096
erase 000bb000:4096
erase 000bc000:4096
erase 000bd000:4096
erase 000be000:4096
erase 000bf000:4096
erase 000c0000:4096
erase 000c1000:4096
erase 000c2000:4096
erase 000c3000:4096
erase 000c4000:4096
erase 000c5000:4096
erase 000c6000:4096
erase 000c7000:4096
erase 000c8000:4096
erase 000c9000:4096
erase 000ca000:4096
erase 000cb000:4096
erase 000cc000:4096
erase 000cd000:4096
erase 000ce000:4096
erase 000cf000:4096
erase 000d0000:4096
erase 000d1000:4096
erase 000d2000:4096
erase 000d3000:4096
erase 000d4000:4096
erase 000d5000:4096
erase 000d6000:4096
erase 000d7000:4096
erase 000d8000:4096
erase 000d9000:4096
erase 000da000:4096
erase 000db000:4096
erase 000dc000:4096
erase 000dd000:4096
erase 000de000:4096
erase 000df000:4096
erase 000e0000:4096
erase 000e1000:4096
erase 000e2000:4096
erase 000e3000:4096
erase 000e4000:4096
erase 000e5000:4096
erase 000e6000:4096
erase 000e7000:4096
erase 000e8000:4096
erase 000e9000:4096
erase 000ea000:4096
erase 000eb000:4096
erase 000ec000:4096
erase 000ed000:4096
erase 000ee000:4096
erase 000ef000:4096
erase 000f0000:4096
erase 000f1000:4096
erase 000f2000:4096
erase 000f3000:4096
erase 000f4000:4096
erase 000f5000:4096
erase 000f6000:4096
erase 000f7000:4096
erase 000f8000:4096
erase 000f9000:4096
erase 000fa000:4096
erase 000fb000:4096
erase 000fc000:4096
erase 000fd000:4096
erase 000fe000:4096
erase 000ff000:4096
0000019299 [app.spiffs] INFO: format res=0
SPIFFS_mount  sz:1048576 logpgsz:256 logblksz:4096 perasz:4096 addr:00000000 fdsz:128 cachesz:1192
0000019300 [app.spiffs] INFO: mount after format res=-10025
0000019301 [app] INFO: mount res=-10025`

I have wired it up as per you instructions / images

don't suppose you have any suggestions??

thanks

**Comment by rickkas7** [comment]
Make sure you use the SpiFlash object for the correct manufacturer. 

Enable trace debugging:

```
SerialLogHandler logHandler(LOG_LEVEL_TRACE);
```

And enable low-level debug:

```
fs.withLowLevelDebug()
```

You'll probably want to make the volume smaller as it will generate a lot of debugging messages.

The important part is the part slightly before mount returns -10025 to see what data is being read out of the chips.

**Comment by medida** [comment]
thanks- setting it to fs.withPhysicalSize(256 * 1024); worked

although the chip is 2mb.

thanks
